-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  phone text,
  address text,
  instagram text,
  twitter text,
  facebook text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  liked_properties jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  phone_number text,
  cadastral_code text,
  property_type text,
  listing_type text,
  status text,
  condition text,
  plan text,
  beds integer NOT NULL DEFAULT 0,
  baths integer NOT NULL DEFAULT 0,
  rooms integer,
  terrace_area numeric,
  kitchen_type text,
  ceiling_height numeric,
  floor_level integer,
  total_floors integer,
  year_built integer,
  featured boolean DEFAULT false,
  has_elevator boolean DEFAULT false,
  has_ventilation boolean DEFAULT false,
  has_air_conditioning boolean DEFAULT false,
  is_accessible boolean DEFAULT false,
  address_street text,
  address_city text,
  address_state text,
  address_zip text,
  address_district text,
  lat numeric DEFAULT 41.7151,
  lng numeric DEFAULT 44.8271,
  agent_name text,
  agent_phone text,
  project_name text,
  instagram_handle text,
  facebook_url text,
  twitter_handle text,
  contact_email text,
  user_id uuid,
  reference_number text,
  has_gas boolean,
  has_loggia boolean,
  building_material text,
  furniture_type text,
  has_fireplace boolean,
  storeroom_type text,
  heating_type text,
  hot_water_type text,
  has_internet boolean,
  has_cable_tv boolean,
  has_dishwasher boolean,
  has_gas_stove boolean,
  has_vent boolean,
  has_electric_kettle boolean,
  has_induction_oven boolean,
  has_microwave boolean,
  has_washing_machine boolean,
  has_tv boolean,
  has_coffee_machine boolean,
  has_audio_system boolean,
  has_heater boolean,
  has_electric_oven boolean,
  has_hair_dryer boolean,
  has_cinema boolean,
  has_refrigerator boolean,
  has_vacuum_cleaner boolean,
  has_dryer boolean,
  has_iron boolean,
  has_co_detector boolean,
  has_smoke_detector boolean,
  has_evacuation_ladder boolean,
  has_fire_fighting_system boolean,
  has_perimeter_cameras boolean,
  has_alarm boolean,
  has_live_protection boolean,
  has_locked_entrance boolean,
  has_locked_yard boolean,
  near_bus_stop boolean,
  near_bank boolean,
  near_subway boolean,
  near_supermarket boolean,
  near_kindergarten boolean,
  near_city_center boolean,
  near_pharmacy boolean,
  near_greenery boolean,
  near_park boolean,
  near_shopping_centre boolean,
  near_school boolean,
  near_old_district boolean,
  parking_type text,
  allows_pets boolean,
  allows_parties boolean,
  allows_smoking boolean,
  has_satellite_tv boolean,
  has_phone_line boolean,
  currency text,
  m2 numeric,
  price_per_m2 numeric,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.property_amenities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  amenity text NOT NULL,
  CONSTRAINT property_amenities_pkey PRIMARY KEY (id),
  CONSTRAINT property_amenities_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  equipment text NOT NULL,
  CONSTRAINT property_equipment_pkey PRIMARY KEY (id),
  CONSTRAINT property_equipment_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  image_url text NOT NULL,
  is_primary boolean DEFAULT false,
  CONSTRAINT property_images_pkey PRIMARY KEY (id),
  CONSTRAINT property_images_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_internet_tv (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  option_name text NOT NULL,
  CONSTRAINT property_internet_tv_pkey PRIMARY KEY (id),
  CONSTRAINT property_internet_tv_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_nearby_places (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  place_name text NOT NULL,
  CONSTRAINT property_nearby_places_pkey PRIMARY KEY (id),
  CONSTRAINT property_nearby_places_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_online_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  service_name text NOT NULL,
  CONSTRAINT property_online_services_pkey PRIMARY KEY (id),
  CONSTRAINT property_online_services_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_security (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  security_feature text NOT NULL,
  CONSTRAINT property_security_pkey PRIMARY KEY (id),
  CONSTRAINT property_security_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_storage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  storage_type text NOT NULL,
  CONSTRAINT property_storage_pkey PRIMARY KEY (id),
  CONSTRAINT property_storage_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);