-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  phone text,
  address text,
  instagram text,
  twitter text,
  facebook text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  liked_properties jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  phone_number text,
  contact_email text,
  instagram_handle text,
  facebook_url text,
  twitter_handle text,
  reference_number text,
  cadastral_code text,
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  m2 numeric,
  beds integer DEFAULT 0,
  baths integer DEFAULT 0,
  rooms integer,
  year_built integer,
  condition text,
  status text,
  featured boolean DEFAULT false,
  terrace_area numeric,
  kitchen_type text,
  ceiling_height numeric,
  floor_level integer,
  total_floors integer,
  amenities ARRAY DEFAULT '{}'::text[],
  equipment ARRAY DEFAULT '{}'::text[],
  internet_tv ARRAY DEFAULT '{}'::text[],
  storage ARRAY DEFAULT '{}'::text[],
  security ARRAY DEFAULT '{}'::text[],
  nearby_places ARRAY DEFAULT '{}'::text[],
  online_services ARRAY DEFAULT '{}'::text[],
  has_elevator boolean DEFAULT false,
  has_ventilation boolean DEFAULT false,
  has_air_conditioning boolean DEFAULT false,
  is_accessible boolean DEFAULT false,
  has_gas boolean DEFAULT false,
  has_loggia boolean DEFAULT false,
  has_fireplace boolean DEFAULT false,
  has_internet boolean DEFAULT false,
  has_cable_tv boolean DEFAULT false,
  has_satellite_tv boolean DEFAULT false,
  has_phone_line boolean DEFAULT false,
  has_vent boolean DEFAULT false,
  has_cinema boolean DEFAULT false,
  has_dishwasher boolean DEFAULT false,
  has_gas_stove boolean DEFAULT false,
  has_electric_kettle boolean DEFAULT false,
  has_induction_oven boolean DEFAULT false,
  has_microwave boolean DEFAULT false,
  has_electric_oven boolean DEFAULT false,
  has_washing_machine boolean DEFAULT false,
  has_tv boolean DEFAULT false,
  has_coffee_machine boolean DEFAULT false,
  has_audio_system boolean DEFAULT false,
  has_heater boolean DEFAULT false,
  has_hair_dryer boolean DEFAULT false,
  has_refrigerator boolean DEFAULT false,
  has_vacuum_cleaner boolean DEFAULT false,
  has_dryer boolean DEFAULT false,
  has_iron boolean DEFAULT false,
  has_co_detector boolean DEFAULT false,
  has_smoke_detector boolean DEFAULT false,
  has_evacuation_ladder boolean DEFAULT false,
  has_fire_fighting_system boolean DEFAULT false,
  has_perimeter_cameras boolean DEFAULT false,
  has_alarm boolean DEFAULT false,
  has_live_protection boolean DEFAULT false,
  has_locked_entrance boolean DEFAULT false,
  has_locked_yard boolean DEFAULT false,
  near_bus_stop boolean DEFAULT false,
  near_bank boolean DEFAULT false,
  near_subway boolean DEFAULT false,
  near_supermarket boolean DEFAULT false,
  near_kindergarten boolean DEFAULT false,
  near_city_center boolean DEFAULT false,
  near_pharmacy boolean DEFAULT false,
  near_greenery boolean DEFAULT false,
  near_park boolean DEFAULT false,
  near_shopping_centre boolean DEFAULT false,
  near_school boolean DEFAULT false,
  near_old_district boolean DEFAULT false,
  allows_pets boolean DEFAULT false,
  allows_parties boolean DEFAULT false,
  allows_smoking boolean DEFAULT false,
  building_material text,
  furniture_type text,
  storeroom_type text,
  heating_type text,
  hot_water_type text,
  parking_type text,
  address_street text,
  address_city text,
  address_district text,
  lat numeric DEFAULT 41.7151,
  lng numeric DEFAULT 44.8271,
  images ARRAY DEFAULT '{}'::text[],
  property_type text,
  listing_type text,
  plan text,
  agent_name text,
  agent_phone text,
  project_name text,
  price_per_m2 numeric,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.properties_backup (
  id uuid,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  title text,
  description text,
  price numeric,
  phone_number text,
  cadastral_code text,
  property_type text,
  listing_type text,
  status text,
  condition text,
  plan text,
  beds integer,
  baths integer,
  rooms integer,
  terrace_area numeric,
  kitchen_type text,
  ceiling_height numeric,
  floor_level integer,
  total_floors integer,
  year_built integer,
  featured boolean,
  has_elevator boolean,
  has_ventilation boolean,
  has_air_conditioning boolean,
  is_accessible boolean,
  address_street text,
  address_city text,
  address_state text,
  address_zip text,
  address_district text,
  lat numeric,
  lng numeric,
  agent_name text,
  agent_phone text,
  project_name text,
  instagram_handle text,
  facebook_url text,
  twitter_handle text,
  contact_email text,
  user_id uuid,
  reference_number text,
  has_gas boolean,
  has_loggia boolean,
  building_material text,
  furniture_type text,
  has_fireplace boolean,
  storeroom_type text,
  heating_type text,
  hot_water_type text,
  has_internet boolean,
  has_cable_tv boolean,
  has_dishwasher boolean,
  has_gas_stove boolean,
  has_vent boolean,
  has_electric_kettle boolean,
  has_induction_oven boolean,
  has_microwave boolean,
  has_washing_machine boolean,
  has_tv boolean,
  has_coffee_machine boolean,
  has_audio_system boolean,
  has_heater boolean,
  has_electric_oven boolean,
  has_hair_dryer boolean,
  has_cinema boolean,
  has_refrigerator boolean,
  has_vacuum_cleaner boolean,
  has_dryer boolean,
  has_iron boolean,
  has_co_detector boolean,
  has_smoke_detector boolean,
  has_evacuation_ladder boolean,
  has_fire_fighting_system boolean,
  has_perimeter_cameras boolean,
  has_alarm boolean,
  has_live_protection boolean,
  has_locked_entrance boolean,
  has_locked_yard boolean,
  near_bus_stop boolean,
  near_bank boolean,
  near_subway boolean,
  near_supermarket boolean,
  near_kindergarten boolean,
  near_city_center boolean,
  near_pharmacy boolean,
  near_greenery boolean,
  near_park boolean,
  near_shopping_centre boolean,
  near_school boolean,
  near_old_district boolean,
  parking_type text,
  allows_pets boolean,
  allows_parties boolean,
  allows_smoking boolean,
  has_satellite_tv boolean,
  has_phone_line boolean,
  currency text,
  m2 numeric,
  price_per_m2 numeric,
  amenities ARRAY,
  equipment ARRAY,
  internet_tv ARRAY,
  storage ARRAY,
  security ARRAY,
  nearby_places ARRAY,
  online_services ARRAY
);
CREATE TABLE public.property_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  image_url text NOT NULL,
  is_primary boolean DEFAULT false,
  CONSTRAINT property_images_pkey PRIMARY KEY (id)
);