// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjkernsgoigbtzdsteby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqa2VybnNnb2lnYnR6ZHN0ZWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjEzNDksImV4cCI6MjA2MTA5NzM0OX0.QAFeihbZCvo9eWS3-r-TFbSEXKEs8DlxaWly-moA8-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);